/**
 * WebDev Practical Project Server API
 * WebDev Practical Project Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maximilian.altmeyer@dfki.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Student } from './student';


export class Answer {
    /**
     * answerID as generated by the database system
     */
    answerID?: number;
    author?: Student;
    /**
     * The answer itself
     */
    answerTo?: number;
    /**
     * The answer itself
     */
    textContent?: string;
    /**
     * Number of all upvotes for this answer subtracted by the number of downvotes
     */
    voteRatio?: number;
    /**
     * The vote that was performed by the student for which studentID was given (either 0,1,-1)
     */
    studentVote?: number;
}
