/**
 * WebDev Practical Project Server API
 * WebDev Practical Project Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maximilian.altmeyer@dfki.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export class Lecture {
    /**
     * lectureID as generated by the database system
     */
    lectureid?: number;
    /**
     * Name of the lecture
     */
    lecturename?: string;
    /**
     * Description of the lecture
     */
    lecturedescription?: string;
}
