/**
 * WebDev Practical Project Server API
 * WebDev Practical Project Server API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maximilian.altmeyer@dfki.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams }               from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';

import { Body1 } from '../model/body1';
import { Body2 } from '../model/body2';
import { Body3 } from '../model/body3';
import { Question } from '../model/question';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';


@Injectable()
export class QuestionService {

    protected basePath = 'http://localhost:5300';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add a new question in a given lecture
     * 
     * @param lectureID lectureID of the lecture in which the question should be posted
     * @param body The textContent of the new question and the author (studentID) of the question
     */
    public addQuestion(lectureID: number, body: Body3): Observable<Question> {
        if (lectureID === null || lectureID === undefined) {
            throw new Error('Required parameter lectureID was null or undefined when calling addQuestion.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addQuestion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/question/byLecture/${encodeURIComponent(String(lectureID))}`,
            body,
            {
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

    /**
     * Returns all questions in the system
     * 
     * @param studentID studentID of the student that requests the questions
     */
    public getQuestions(studentID: number): Observable<Array<Question>> {
        if (studentID === null || studentID === undefined) {
            throw new Error('Required parameter studentID was null or undefined when calling getQuestions.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (studentID !== undefined) {
            queryParameters = queryParameters.set('studentID', <any>studentID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/question`,
            {
                params: queryParameters,
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

    /**
     * Find questions by lectureID
     * Returns all questions for a lecture
     * @param lectureID lectureID of corresponding lecture
     * @param studentID studentID of the student that requests the questions
     */
    public getQuestionsByLectureID(lectureID: number, studentID: number): Observable<Array<Question>> {
        if (lectureID === null || lectureID === undefined) {
            throw new Error('Required parameter lectureID was null or undefined when calling getQuestionsByLectureID.');
        }
        if (studentID === null || studentID === undefined) {
            throw new Error('Required parameter studentID was null or undefined when calling getQuestionsByLectureID.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (studentID !== undefined) {
            queryParameters = queryParameters.set('studentID', <any>studentID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/question/byLecture/${encodeURIComponent(String(lectureID))}`,
            {
                params: queryParameters,
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

    /**
     * Find question by questionID
     * Returns question for a questionID
     * @param questionID questionID of corresponding question
     * @param studentID studentID of the student that requests the questions
     */
    public getQuestionsByQuestionID(questionID: number, studentID: number): Observable<Question> {
        if (questionID === null || questionID === undefined) {
            throw new Error('Required parameter questionID was null or undefined when calling getQuestionsByQuestionID.');
        }
        if (studentID === null || studentID === undefined) {
            throw new Error('Required parameter studentID was null or undefined when calling getQuestionsByQuestionID.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (studentID !== undefined) {
            queryParameters = queryParameters.set('studentID', <any>studentID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/question/${encodeURIComponent(String(questionID))}`,
            {
                params: queryParameters,
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

    /**
     * Update a question
     * 
     * @param questionID questionID of corresponding question
     * @param body The new textContent of the question and the studentID to check if it matches the author of the question
     */
    public updateQuestion(questionID: number, body: Body1): Observable<Question> {
        if (questionID === null || questionID === undefined) {
            throw new Error('Required parameter questionID was null or undefined when calling updateQuestion.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateQuestion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/question/${encodeURIComponent(String(questionID))}`,
            body,
            {
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

    /**
     * Vote for a question. NOTE that voting is only possible once per user and question/answer!
     * 
     * @param questionID questionID of corresponding question
     * @param body The vote (-1 or 1) for a . NOTE that voting is only possible once per user and question/answer!
     */
    public voteQuestion(questionID: number, body: Body2): Observable<Question> {
        if (questionID === null || questionID === undefined) {
            throw new Error('Required parameter questionID was null or undefined when calling voteQuestion.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling voteQuestion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/question/vote/${encodeURIComponent(String(questionID))}`,
            body,
            {
                headers: headers,
                withCredentials: this.configuration.withCredentials,
            }
        );
    }

}
